# -*- coding: utf-8 -*-
"""05_feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM1Rmat6DI9Zw-3sLgH_9UzpCUNSrWel
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import NumericType
from pyspark.ml.feature import VectorAssembler

# -------------------------------------------------------
# Paths
# -------------------------------------------------------
HDFS_CLEANED = "hdfs://namenode:9000/user/bigdata/ids2017/processed/cleaned"
HDFS_ML_READY = "hdfs://namenode:9000/user/bigdata/ids2017/processed/ml_ready_binary"

# -------------------------------------------------------
# Spark Session
# -------------------------------------------------------
spark = (
    SparkSession.builder
    .appName("IDS2017-Member2-FeatureEngineering")
    .master("spark://spark-master:7077")
    .config("spark.executor.memory", "1500m")
    .config("spark.executor.cores", "1")
    .config("spark.driver.memory", "512m")
    .config("spark.sql.shuffle.partitions", "4")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

# -------------------------------------------------------
# Step 1: Read Member 1 cleaned data
# -------------------------------------------------------
print("Step 1: Reading Member 1 cleaned Parquet")

df = spark.read.parquet(HDFS_CLEANED)

print("Rows:", df.count())
print("Columns:", len(df.columns))
df.printSchema()

# -------------------------------------------------------
# Step 2: Check original labels
# -------------------------------------------------------
print("Step 2: Original label distribution")

df.groupBy("label").count().orderBy(F.desc("count")).show(50, truncate=False)

# -------------------------------------------------------
# Step 3: Convert labels to binary
# BENIGN = 0
# Any attack = 1
# -------------------------------------------------------
print("Step 3: Creating binary label")

df = df.withColumnRenamed("label", "label_original")

df = df.withColumn(
    "label",
    F.when(F.col("label_original") == "BENIGN", F.lit(0.0)).otherwise(F.lit(1.0))
)

print("Binary label distribution:")
df.groupBy("label").count().orderBy("label").show()

# -------------------------------------------------------
# Step 4: Feature Engineering
# -------------------------------------------------------
print("Step 4: Creating engineered features")

# total packets = forward packets + backward packets
if "fwd_packets_count" in df.columns and "bwd_packets_count" in df.columns:
    df = df.withColumn(
        "total_packets",
        F.col("fwd_packets_count") + F.col("bwd_packets_count")
    )

# total payload bytes = forward payload + backward payload
if "fwd_total_payload_bytes" in df.columns and "bwd_total_payload_bytes" in df.columns:
    df = df.withColumn(
        "total_payload_bytes",
        F.col("fwd_total_payload_bytes") + F.col("bwd_total_payload_bytes")
    )

# average payload per packet
if "total_payload_bytes" in df.columns and "total_packets" in df.columns:
    df = df.withColumn(
        "avg_payload_per_packet",
        F.when(
            F.col("total_packets") > 0,
            F.col("total_payload_bytes") / F.col("total_packets")
        ).otherwise(F.lit(0.0))
    )

# ratio between forward and backward packets
if "fwd_packets_count" in df.columns and "bwd_packets_count" in df.columns:
    df = df.withColumn(
        "fwd_bwd_packet_ratio",
        F.when(
            F.col("bwd_packets_count") > 0,
            F.col("fwd_packets_count") / F.col("bwd_packets_count")
        ).otherwise(F.lit(0.0))
    )

# log-transformed features to reduce impact of very large values
if "duration" in df.columns:
    df = df.withColumn(
        "log_duration",
        F.log1p(F.when(F.col("duration") >= 0, F.col("duration")).otherwise(F.lit(0.0)))
    )

if "bytes_rate" in df.columns:
    df = df.withColumn(
        "log_bytes_rate",
        F.log1p(F.when(F.col("bytes_rate") >= 0, F.col("bytes_rate")).otherwise(F.lit(0.0)))
    )

if "packets_rate" in df.columns:
    df = df.withColumn(
        "log_packets_rate",
        F.log1p(F.when(F.col("packets_rate") >= 0, F.col("packets_rate")).otherwise(F.lit(0.0)))
    )

# -------------------------------------------------------
# Step 5: Detect numeric feature columns
# Use NumericType so we include Double, Integer, Long, etc.
# -------------------------------------------------------
print("Step 5: Selecting numeric feature columns")

ignore_cols = {"label", "label_original"}

numeric_cols = [
    field.name
    for field in df.schema.fields
    if field.name not in ignore_cols and isinstance(field.dataType, NumericType)
]

print("Number of numeric feature columns:", len(numeric_cols))

if len(numeric_cols) == 0:
    raise ValueError("No numeric feature columns found. Check schema.")

# Cast all numeric columns to double for Spark MLlib consistency
for c in numeric_cols:
    df = df.withColumn(c, F.col(c).cast("double"))

# -------------------------------------------------------
# Step 6: Convert NaN values to null
# -------------------------------------------------------
print("Step 6: Converting NaN values to null")

for c in numeric_cols:
    df = df.withColumn(
        c,
        F.when(F.isnan(F.col(c)), None).otherwise(F.col(c))
    )

# -------------------------------------------------------
# Step 7: Outlier handling using percentile capping
# Cap values below 1st percentile and above 99th percentile
# -------------------------------------------------------
print("Step 7: Handling outliers using percentile capping")

LOWER_Q = 0.01
UPPER_Q = 0.99
REL_ERROR = 0.01

quantiles = df.approxQuantile(numeric_cols, [LOWER_Q, UPPER_Q], REL_ERROR)

for col_name, bounds in zip(numeric_cols, quantiles):
    if len(bounds) == 2:
        lower, upper = bounds

        # Skip invalid or constant columns
        if lower is not None and upper is not None and lower < upper:
            df = df.withColumn(
                col_name,
                F.when(F.col(col_name) < lower, F.lit(lower))
                 .when(F.col(col_name) > upper, F.lit(upper))
                 .otherwise(F.col(col_name))
            )

print("Outlier capping completed")

# -------------------------------------------------------
# Step 8: Handle missing values after outlier capping
# -------------------------------------------------------
print("Step 8: Handling missing values")

df = df.fillna(0.0, subset=numeric_cols)

# -------------------------------------------------------
# Step 9: Validate important columns after preprocessing
# -------------------------------------------------------
print("Step 9: Validation summary for important columns")

important_cols = [
    "duration",
    "bytes_rate",
    "packets_rate",
    "total_packets",
    "total_payload_bytes",
    "avg_payload_per_packet",
    "fwd_bwd_packet_ratio",
    "log_duration",
    "log_bytes_rate",
    "log_packets_rate"
]

existing_important_cols = [c for c in important_cols if c in df.columns]

if existing_important_cols:
    df.select(existing_important_cols).summary(
        "count", "min", "max", "mean", "stddev"
    ).show(truncate=False)

# -------------------------------------------------------
# Step 10: Assemble features vector for Spark MLlib
# -------------------------------------------------------
print("Step 10: Assembling features vector")

assembler = VectorAssembler(
    inputCols=numeric_cols,
    outputCol="features",
    handleInvalid="keep"
)

df_ml = assembler.transform(df).select(
    "features",
    "label",
    "label_original"
)

# -------------------------------------------------------
# Step 11: Final validation
# -------------------------------------------------------
print("Step 11: Final ML-ready dataset validation")

df_ml.printSchema()

print("Final row count:", df_ml.count())

print("Final binary label distribution:")
df_ml.groupBy("label").count().orderBy("label").show()

print("Original labels still available:")
df_ml.groupBy("label_original").count().orderBy(F.desc("count")).show(50, truncate=False)

# -------------------------------------------------------
# Step 12: Save final ML-ready dataset
# -------------------------------------------------------
print("Step 12: Writing ML-ready dataset to HDFS")

df_ml.write.mode("overwrite").parquet(HDFS_ML_READY)

print("Done.")
print("Output saved to:")
print(HDFS_ML_READY)

spark.stop()